[book]
authors = ["x5zone"]
language = "zh-cn"
src = "."
title = "ğŸŒŒ ä¹Œæœ‰ä¹‹ä¹¡"

[output.html]
# å¼€å¯æ·±è‰²æ¨¡å¼
default-theme = "navy"
preferred-dark-theme = "navy"

additional-css = ["custom.css"]

# å…è®¸åœ¨ GitHub ä¸Šç¼–è¾‘
git-repository-url = "https://github.com/x5zone/x5zone.github.io"

# é…ç½®æœç´¢
[output.html.search]
limit-results = 30